version: "3.7"
services:
  api:
    build: "./api"
    container_name: api
    env_file:
      - ./app.env
    volumes:
      - "./api:/app"
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
  db:
    image: mongo:latest
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  cache:
    image: redis:4-alpine
    container_name: cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
